FROM golang:1.24-alpine AS builder

WORKDIR /app

RUN apk add --no-cache make

COPY go.mod go.sum ./
RUN go mod download

COPY Makefile ./
COPY jacked/ ./jacked
COPY example/ ./example

RUN make build-release 