name: Security and Load Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
        check-latest: true

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y jq curl

    - name: Run Security Tests
      run: |
        mkdir -p tests
        ./scripts/security-test.sh > tests/security.md

    - name: Run Load Tests
      run: |
        ./scripts/load-test.sh > tests/load-test.md

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          tests/security.md
          tests/load-test.md
        retention-days: 7 